### ISSUE TITLE
ビルドサイズが小さくなる魔法の呪文

### ISSUE THREAD

**Issue by Azu0925** [HamadaTomoki/ap4s-submitter#1]
Cargo.tomlに以下をこぴぺ
```toml
[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
```

ビルドする
```shell
cargo build --release
```

**Comment by HamadaTomoki** [comment]
神ィィィッ

**Comment by novum-d** [comment]
GitHub Marketplaceで[Rust Release binary](https://github.com/marketplace/actions/rust-release-binary)なるものを発見したのでこれを使用する

**Comment by novum-d** [comment]
ワークフローでなぜか`release`イベントがトリガーされないのでpushに変更
https://github.com/HamadaTomoki/ap4s-submitter/blob/b40803424ca11931a9a0c2585672bcb9982d573c/.github/workflows/release.yml#L3-L4

以下で言及されていたので参考にして解決✨
https://github.com/rust-build/rust-build.action/issues/46#issuecomment-1213628019
